---
abstract: 'Generate QR Code with Imager using libqrencode'
author:
  - 'Yoshiki KURIHARA <kurihara at cpan.org>'
build_requires:
  Imager: 0.55
  Test::More: 0
configure_requires:
  Imager: 0.55
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Imager-QRCode
no_index:
  directory:
    - inc
    - t
    - examples
    - examples
version: 0.031
