---
abstract: 'Generate QR Code with Imager using libqrencode'
author:
  - 'Yoshiki KURIHARA <kurihara at cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Imager: 0.55
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
  Imager: 0.55
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Imager-QRCode
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  XSLoader: 0.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.031
